# https://www.domysee.com/blogposts/reverse-proxy-nginx-docker-compose
version: '3.4'
services:
  app:
    container_name: py_template
    build: .
    command: ["make", "start"]
    volumes:
      - './Makefile:/app/Makefile'
      - './main.py:/app/main.py'
      - './input:/app/input'
      - './output:/app/output'
      - './logs:/app/logs'
      - './functions:/app/functions'